# Generated by Django 3.2.5 on 2021-09-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0008_alter_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('first_name', models.CharField(help_text='First name of the volunteer', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the Volunteer', max_length=100)),
                ('nic', models.CharField(help_text='NIC number of the volunteer', max_length=15, unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
