# Generated by Django 3.2.5 on 2021-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.CharField(max_length=100)),
                ('water', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('artificial_bare_ground', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('artificial_natural_ground', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('woody', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('non_woody_cultivated', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('non_woody_natural', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('mean_ndvi', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('mean_burn_index', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
