# Generated by Django 3.2.5 on 2021-09-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolunteerOpportunity',
            new_name='ForestStats',
        ),
    ]
