# Generated by Django 3.2.5 on 2021-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_stats', '0002_rename_volunteeropportunity_foreststats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreststats',
            name='artificial_bare_ground',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='foreststats',
            name='artificial_natural_ground',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='foreststats',
            name='mean_burn_index',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='foreststats',
            name='mean_ndvi',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='foreststats',
            name='non_woody_cultivated',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='foreststats',
            name='non_woody_natural',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='foreststats',
            name='water',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='foreststats',
            name='woody',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
