# Generated by Django 3.2.5 on 2021-09-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0010_alter_volunteer_dob'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deforestationreports',
            name='action_description',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deforestationreports',
            name='district',
            field=models.CharField(default='Colombo', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deforestationreports',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deforestationreports',
            name='recent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deforestationreports',
            name='severity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deforestationreports',
            name='special_notes',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deforestationreports',
            name='volunteer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
            preserve_default=False,
        ),
    ]
