# Generated by Django 3.2.5 on 2021-09-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210930_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deforestationreports',
            name='img_url',
        ),
    ]
