# Generated by Django 3.2.5 on 2021-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210930_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestationreports',
            name='action_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='deforestationreports',
            name='district',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='deforestationreports',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deforestationreports',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deforestationreports',
            name='recent',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='deforestationreports',
            name='severity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='deforestationreports',
            name='special_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
