# Generated by Django 3.2.5 on 2021-09-30 17:48

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0010_alter_volunteer_dob'),
        ('report', '0006_auto_20210930_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeforestationReports',
            new_name='DeforestationReport',
        ),
        migrations.CreateModel(
            name='ReportPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.deforestationreport')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
