# Generated by Django 3.2.5 on 2021-09-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210930_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportPhotos',
            new_name='ReportPhoto',
        ),
    ]
