# Generated by Django 3.2.5 on 2021-09-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_rename_reportphotos_reportphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestationreport',
            name='special_notes',
            field=models.CharField(max_length=500),
        ),
    ]
