# Generated by Django 3.2.5 on 2021-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_deforestationreport_special_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestationreport',
            name='action_description',
            field=models.CharField(blank=True, max_length=750),
        ),
        migrations.AlterField(
            model_name='deforestationreport',
            name='recent',
            field=models.CharField(blank=True, max_length=750),
        ),
        migrations.AlterField(
            model_name='deforestationreport',
            name='special_notes',
            field=models.CharField(blank=True, max_length=750),
        ),
    ]
