# Generated by Django 3.2.5 on 2021-09-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='district',
        ),
        migrations.RemoveField(
            model_name='volunteeropportunity',
            name='volunteer',
        ),
    ]
