# Generated by Django 3.2.5 on 2021-09-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0005_alter_vio_state'),
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='vio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vio.vio'),
        ),
    ]
