# Generated by Django 3.2.5 on 2021-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_alter_opportunity_vio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='state',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('COMPLETED', 'Complete')], default='PENDING', max_length=25),
        ),
    ]
