# Generated by Django 3.2.5 on 2021-09-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_volunteer_state'),
        ('opportunity', '0002_auto_20210920_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='district',
            field=models.CharField(blank=True, help_text='District of the Opportunity residence', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity'),
        ),
    ]
