# Generated by Django 3.2.5 on 2021-09-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_alter_volunteeropportunity_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='end_date',
            field=models.DateField(default='2020-10-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='goals',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='numVolunteers',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='start_date',
            field=models.DateField(default='2020-10-12'),
            preserve_default=False,
        ),
    ]
