# Generated by Django 3.2.5 on 2021-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_auto_20210929_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='contactPersonNumber',
            field=models.CharField(default='0777238031', help_text='Contact number of volunteer', max_length=15),
            preserve_default=False,
        ),
    ]
