# Generated by Django 3.2.5 on 2021-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_opportunity_contactpersonnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='state',
            field=models.CharField(choices=[('DELETE', 'Deleted'), ('UNAPPROVED', 'Unapproved'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('COMPLETED', 'Complete')], default='UNAPPROVED', max_length=25),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='state',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('UNACCEPTED_COMPLETE', 'Unaccepted_Complete'), ('COMPLETED', 'Complete')], default='PENDING', max_length=25),
        ),
    ]
