# Generated by Django 3.2.5 on 2021-11-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_auto_20211020_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='address',
            field=models.TextField(blank=True, help_text='Register address of the Opportunity', max_length=250),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(help_text='Description of the Opportunity', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='district',
            field=models.TextField(blank=True, help_text='District of the Opportunity residence', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='goals',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.TextField(help_text='name of the Opportunity', max_length=100),
        ),
    ]
