# Generated by Django 3.2.5 on 2021-09-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('VOL', 'Volunteer'), ('VIO', 'Vio'), ('AD', 'Admin')], default='VOL', max_length=50, verbose_name='user_type'),
        ),
    ]
