# Generated by Django 3.2.5 on 2021-09-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(default=12345678, max_length=100, verbose_name='email_token'),
            preserve_default=False,
        ),
    ]
