# Generated by Django 3.2.5 on 2021-09-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210911_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('EMAIL_UNVERIFIED', 'Email_Unverified'), ('DELETE', 'Deleted'), ('UNAPPROVED', 'Unapproved'), ('APPROVED', 'Approved')], default='EMAIL_UNVERIFIED', max_length=25),
        ),
    ]
