# Generated by Django 3.2.5 on 2021-09-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_email_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('first_name', models.CharField(help_text='First name of the volunteer', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the Volunteer', max_length=100)),
                ('nic', models.CharField(help_text='NIC number of the volunteer', max_length=15, unique=True)),
                ('nameNIC', models.CharField(help_text='Name as stated in the NIC', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('UN', 'Unspecified')], help_text='gender of the volunteer', max_length=15)),
                ('district', models.CharField(help_text='District of the volunteer residence', max_length=100)),
                ('address', models.CharField(help_text='Volunteers address of residence', max_length=100)),
                ('imageUrl', models.CharField(blank=True, help_text='Volunteers image url', max_length=100)),
                ('specialConditions', models.CharField(blank=True, help_text='Any special conditions of the user', max_length=250)),
                ('preferredLanguage', models.CharField(choices=[('S', 'Sinhala'), ('E', 'English'), ('T', 'Tamil')], default='S', help_text='Preferred Language of the volunteer', max_length=100)),
                ('highestEducation', models.CharField(choices=[('OL', 'OL'), ('AL', 'AL'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], help_text='Highest Education of the volunteer', max_length=100)),
                ('state', models.CharField(choices=[('D', 'Deleted'), ('U', 'Unapproved'), ('A', 'Approved')], default='U', help_text='state of the volunteer', max_length=15)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
