# Generated by Django 3.2.5 on 2021-09-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, help_text='Volunteers address of residence', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='district',
            field=models.CharField(blank=True, help_text='District of the volunteer residence', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('UN', 'Unspecified')], help_text='gender of the volunteer', max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='highestEducation',
            field=models.CharField(blank=True, choices=[('OL', 'OL'), ('AL', 'AL'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], help_text='Highest Education of the volunteer', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='nameNIC',
            field=models.CharField(blank=True, help_text='Name as stated in the NIC', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preferredLanguage',
            field=models.CharField(blank=True, choices=[('S', 'Sinhala'), ('E', 'English'), ('T', 'Tamil')], default='S', help_text='Preferred Language of the volunteer', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=models.CharField(blank=True, choices=[('D', 'Deleted'), ('U', 'Unapproved'), ('A', 'Approved')], default='U', help_text='state of the volunteer', max_length=15),
        ),
    ]
