# Generated by Django 3.2.5 on 2021-09-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_remove_volunteer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNSPECIFIED', 'Unspecified')], help_text='gender of the volunteer', max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='highestEducation',
            field=models.CharField(blank=True, choices=[('OL', 'OL'), ('AL', 'AL'), ('UNDERGRADUATE', 'Undergraduate'), ('POSTGRADUATE', 'Postgraduate')], help_text='Highest Education of the volunteer', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preferredLanguage',
            field=models.CharField(blank=True, choices=[('SINHALA', 'Sinhala'), ('ENGLISH', 'English'), ('TAMIL', 'Tamil')], default='SINHALA', help_text='Preferred Language of the volunteer', max_length=100),
        ),
    ]
