# Generated by Django 3.2.5 on 2021-09-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20210911_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='state',
            field=models.CharField(choices=[('EMAIL_UNVERIFIED', 'Email_Unverified'), ('DELETE', 'Deleted'), ('UNAPPROVED', 'Unapproved'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='EMAIL_UNVERIFIED', max_length=25),
        ),
    ]
