# Generated by Django 3.2.5 on 2021-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_alter_volunteer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contactNumber',
            field=models.CharField(default='0776685899', help_text='Contact number of volunteer', max_length=15),
            preserve_default=False,
        ),
    ]
