# Generated by Django 3.2.5 on 2021-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_volunteer_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='dob',
            field=models.DateTimeField(default='1998-10-17'),
            preserve_default=False,
        ),
    ]
