# Generated by Django 3.2.5 on 2021-09-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_volunteer_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='specialConditions',
        ),
    ]
