# Generated by Django 3.2.5 on 2021-09-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_email_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('name', models.CharField(help_text='name of the Vio', max_length=100)),
                ('description', models.CharField(help_text='Description of the Vio', max_length=255)),
                ('imageUrl', models.CharField(blank=True, help_text='VIO image url', max_length=100)),
                ('state', models.CharField(choices=[('D', 'Deleted'), ('U', 'Unapproved'), ('A', 'Approved')], default='U', help_text='Vio state', max_length=20)),
                ('registrationNo', models.CharField(blank=True, help_text='Registration Number of the Vio', max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
