# Generated by Django 3.2.5 on 2021-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0004_vio_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vio',
            name='state',
            field=models.CharField(choices=[('DELETE', 'Deleted'), ('UNAPPROVED', 'Unapproved'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='UNAPPROVED', max_length=25),
        ),
    ]
