# Generated by Django 3.2.5 on 2021-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0005_alter_vio_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vio',
            name='contactNumber',
            field=models.CharField(default='077238066', help_text='Contact number of volunteer', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vio',
            name='registrationDate',
            field=models.DateTimeField(default='2017-10-01'),
            preserve_default=False,
        ),
    ]
