# Generated by Django 3.2.5 on 2021-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio', '0006_auto_20210927_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vio',
            name='registrationDate',
            field=models.DateField(),
        ),
    ]
